In [ ]:
# We gonna create a layer which does not exists yet in the deep learning framework.

In [11]:
### Layers without parameters


In [12]:
from mxnet import np, npx
from mxnet.gluon import nn
  
npx.set_np()

In [13]:
class CenteredLayer(nn.Block):
  def __init__(self, **kwargs):
    super().__init__(**kwargs)
  def forward(self, X):
    return X - X.mean()


In [14]:
#lets give some data 
layer = CenteredLayer()
layer(np.array([1, 2, 3, 4, 5]))

array([-2., -1.,  0.,  1.,  2.])

In [15]:
net = nn.Sequential()
net.add(nn.Dense(128), CenteredLayer())
net.initialize()

In [16]:
Y = net(np.random.uniform(size=(4, 8)))
Y.mean()


array(3.783498e-10)

In [17]:
###

In [18]:
#### With Parameters

In [24]:
class MyDense(nn.Block):
  def __init__(self, units, in_units, **kwargs):
    super().__init__(**kwargs)
    self.weight = self.params.get('weight', shape=(in_units, units))
    self.bias = self.params.get('bias', shape=(units,))
  def forward(self, x):
    linear = np.dot(x, self.weight.data(ctx=x.ctx)) + self.bias.data(ctx=x.ctx)
    return npx.relu(linear)

In [25]:
dense = MyDense(units=3, in_units=5)
dense.params

mydense0_ (
  Parameter mydense0_weight (shape=(5, 3), dtype=<class 'numpy.float32'>)
  Parameter mydense0_bias (shape=(3,), dtype=<class 'numpy.float32'>)
)

In [26]:
dense.initialize()
dense(np.random.uniform(size=(2, 5)))


array([[0.        , 0.01633355, 0.        ],
       [0.        , 0.01581812, 0.        ]])

In [27]:
net = nn.Sequential()
net.add(MyDense(8, in_units=64), MyDense(1, in_units=8))
net.initialize()
net(np.random.uniform(size=(2, 64)))

array([[0.06508517],
       [0.0615553 ]])